### ISSUE TITLE
项目烂尾了？

### ISSUE THREAD

**Issue by lyingfromyou** [qiurunze123/miaosha#112]
项目烂尾了？

**Comment by LaoshuBaby** [comment]
我也好奇，或许可能真的不想接盘了吗？

甚至这种东西都没人管了 https://github.com/qiurunze123/miaosha/pull/104

~~虽然如此，但是它确实已经是一个经典的项目了~~

**Comment by anruence** [comment]
> 项目烂尾了？

@lyingfromyou @LaoshuBaby 没有的哈，作者近期较忙，正在琢磨做一套更完整、易用的方案

**Comment by banana-boy484** [comment]
为给我发邮件？？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiurunze123/miaosha"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 晚上10:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [qiurunze123/miaosha] 项目烂尾了？ (#112)





  
项目烂尾了？
  
@lyingfromyou @LaoshuBaby 没有的哈，作者近期较忙，正在琢磨做一套更完整、易用的方案
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
